### PR TITLE
3rd Milestone Game logic

### PR DESCRIPTION
**Pull request by cvilla714**
On this branch, we created the game logic accounting for 

- when the player tries to pick a spot that was already taken
- when the player tries to input a letter instead of an integer between 1 to 9
- We also validated the input values from each player
- We validate the winner by matching the winner combination with the board
- We inform if there is a winner or if the game ends in a draw

### CODE REVIEW

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

## Hi :wave: @cvilla714 and @kenderb 
### You've done a fantastic job and I must commend you for that. :muscle: . I also noticed you have a very nice intro message for players which is very nice
### However, you need to effect some changes before this milestone can be approved.

## [MANDATORY]

- [x] No `puts/print` and `get.chomp` outside `main.rb` file. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone3/only_main_print.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

- [x] When I try to play the game, after providing my name and choosing my piece (**X** or **O**), I get that :point_down: . I can't see the board.
image

- [x] Please, make sure the application can change active player

- [x] All game-logic related resources (classes and/or modules) are kept in the `lib` directory. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/lib_dir_exist.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

### Effect the changes and submit for another review.
## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Review by ebeagusamuel — CHANGES_REQUESTED** [review]
# Changes Required :recycle: 
Hello @team.
- You have done nice work in building the logic of the tic-tac-toe game :+1:
- Your programs run smoothly and the game flows well.
However, there are some requirements for this milestone that you are yet to meet, and therefore to get this milestone approved you have to ensure this milestone meets those requirements.
### Changes to make :writing_hand: 
- [x] All game-logic related resources (classes and/or modules) are kept in the `lib` directory. ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone1/lib_dir_exist.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/)). The logic for your game is currently in the main.rb file in the bin folder. You should move all method/classes that handles the logic of your game to the lib folder.
- [x] [Optional] To make your code even more organized, each class or module should have its own file in the lib folder(e.g game.rb, board.rb) and you can then require those files wherever you need to use the code in the file.
Please submit another review request when you've made the changes.
Happy coding :+1: 
slack(@ebeagusamuel)

**Review by Srjnnnn — CHANGES_REQUESTED** [review]
### ### ### Changes Required :recycle: :stop_sign: 
You've done a great job but still, there are things to do. :smile: 
Your game doesn't accept repetitive inputs :+1: 

### Game issues
- [x] Right now when someone has won or when there is a draw the game returns as Game Over. Please Fix this issue to print just whether congratulations message or Game Over message.
- [x] Your game can start without a player's name. Please fix this issue as well.
### Code Issues:
- [ ]  Optional: You can make a lighter main.rb. All you need to do is create some methods inside logic.rb and call those methods inside the main.rb.

Kindly fix those issues and submit for a re-review.
If you have confusion about the review, please reach me via Slack.
Eyüp Sercan UYGUR

**Review by Georjane — APPROVED** [review]
# Status: PR Approved ✔️
## Hi @cvilla714 and @kenderb 🙌

Great job implementing the changes required by the previous TSEs. 👏
Your Tic Tac Toe meets the minimum requirements for the project to be valid and I enjoyed playing your game.
You can go ahead and merge this PR. 

Goodluck on the next milestone and Happy Coding! 💻

**Pull request merged**
